default_platform(:ios)

XCODEPROJ = "App/App.xcodeproj"
SCHEME = "App"
APP_IDENTIFIER = "love.collab.app"

platform :ios do
  desc "Build, sign and upload a new build to TestFlight"
  lane :beta do
    key_id = ENV.fetch("ASC_KEY_ID")
    issuer_id = ENV.fetch("ASC_ISSUER_ID")
    team_id = ENV.fetch("APPLE_TEAM_ID")
    key_path = ENV.fetch("ASC_KEY_PATH")

    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: key_path
    )

    setup_ci

    match(
      type: "appstore",
      readonly: true,
      api_key: api_key
    )

    increment_build_number(
      xcodeproj: XCODEPROJ,
      build_number: ENV.fetch("BUILD_NUMBER")
    )

    profile_name = "match AppStore #{APP_IDENTIFIER}"
    update_code_signing_settings(
      path: XCODEPROJ,
      use_automatic_signing: false,
      team_id: team_id,
      code_sign_identity: "Apple Distribution",
      profile_name: profile_name,
      bundle_identifier: APP_IDENTIFIER
    )

    build_app(
      project: XCODEPROJ,
      scheme: SCHEME,
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          APP_IDENTIFIER => profile_name
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
