default_platform(:ios)

XCODEPROJ = "App/App.xcodeproj"
SCHEME = "App"

platform :ios do
  desc "Build, sign and upload a new build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID"),
      issuer_id: ENV.fetch("ASC_ISSUER_ID"),
      key_content: ENV.fetch("ASC_KEY_CONTENT"),
      is_key_content_base64: true
    )

    increment_build_number(
      xcodeproj: XCODEPROJ,
      build_number: ENV.fetch("BUILD_NUMBER")
    )

    team_id = ENV.fetch("APPLE_TEAM_ID")
    build_app(
      project: XCODEPROJ,
      scheme: SCHEME,
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates DEVELOPMENT_TEAM=#{team_id}",
      export_options: {
        signingStyle: "automatic",
        teamID: team_id
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
